#### A. Standard data format


##### When data can take on any range of values, it makes it difficult to interpret. Therefore, data scientists will convert the data into a standard format to make it easier to understand. The standard format refers to data that has 0 mean and unit variance (i.e. standard deviation = 1), and the process of converting data into this format is called data standardization.

#### Data standardization is a relatively simple process. For each data value, **x**, we subtract the overall mean of the data, **μ**, then divide by the overall standard deviation, **σ** . The new value, **z** , represents the standardized data value. Thus, the formula for data standardization is:
#                                                                       z=(x-μ)/σ

In [2]:
import numpy as np

In [3]:
arr=np.array([[2100,   10,  800],
       [2500,   11,  850],
       [1800,   10,  760],
       [2000,   12,  800],
       [2300,   11,  810]])

In [4]:
from sklearn.preprocessing import scale

In [33]:
std_arr=scale(arr)

In [34]:
std_arr

array([[-0.16552118, -1.06904497, -0.1393466 ],
       [ 1.4896906 ,  0.26726124,  1.60248593],
       [-1.40693001, -1.06904497, -1.53281263],
       [-0.57932412,  1.60356745, -0.1393466 ],
       [ 0.66208471,  0.26726124,  0.2090199 ]])

std_arr.mean(axis=0)

In [35]:
std_arr.mean(axis=0)

array([ 2.22044605e-17, -9.76996262e-16,  5.55111512e-18])

In [38]:
col_means = std_arr.mean(axis=0).round(decimals=3)
col_means

array([ 0., -0.,  0.])

In [23]:
(std_arr[0][0]+std_arr[1][0]+std_arr[2][0]+std_arr[3][0]+std_arr[4][0])/5 #[row,colums]

2.2204460492503132e-17

In [24]:
std_arr.mean(axis=1)

array([-0.45797092,  1.11981259, -1.33626254,  0.29496558,  0.37945529])

In [40]:
std_arr.std(axis=0)

array([1., 1., 1.])

In [41]:
std_arr.std(axis=1)

array([0.43222671, 0.604601  , 0.19581544, 0.94259366, 0.20125864])