### Data Range

#### Create a function to compress data into a specific range of values.


#### Apart from standardizing data, we can also scale data by compressing it into a fixed range. One of the biggest use cases for this is **compressing data into the range [0, 1]**. This allows us to view the data in terms of **proportions**, or **percentages**, based on the **minimum** and **maximum** values in the dat


#### For a given data value, **x**, we first compute the proportion of the value with respect to the **min** and **max** of the data **dmin** and **dmax**, respectively).

## (X<sub>prop</sub> = $\frac{x-d_(min)}{d_(max)-d(min)}$)

In [2]:
import numpy as np

In [4]:
arr=np.array([[ 1.2,  3.2],
       [-0.3, -1.2],
       [ 6.5, 10.1],
       [ 2.2, -8.4]])

In [6]:
import numpy as np

####  The MinMaxScaler object contains a function called **fit_transform** , which allows it to take in the input data array and then output the scaled data. The function is a combination of the object's fit and transform functions, where the former takes in an input data array and the latter transforms a (possibly different) array based on the data from the input to the fit function

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
data_scaler=MinMaxScaler()

In [10]:
data_scaler.fit_transform(arr)

array([[0.22058824, 0.62702703],
       [0.        , 0.38918919],
       [1.        , 1.        ],
       [0.36764706, 0.        ]])

In [11]:
# costume scaler

In [14]:
costume_scaler=MinMaxScaler(feature_range=(0,100)) 

In [15]:
costume_scaler.fit_transform(arr)

array([[ 22.05882353,  62.7027027 ],
       [  0.        ,  38.91891892],
       [100.        , 100.        ],
       [ 36.76470588,   0.        ]])

In [16]:
arr=np.array([[ 1.2, -0.5],
       [ 5.3,  2.3],
       [-3.3,  4.1]])

In [18]:
arr

array([[ 1.2, -0.5],
       [ 5.3,  2.3],
       [-3.3,  4.1]])