In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

### Range

In [3]:
np.arange(5) 

array([0, 1, 2, 3, 4])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### start is inclusive end no exclusive i.e: range from 0  to 9 


## casting array to another type

In [5]:
arr=np.array([0,1,23,45,])

In [7]:
arrfloat=arr.astype(np.float32)

In [8]:
arrfloat

array([ 0.,  1., 23., 45.], dtype=float32)

## NaN in array

In [9]:
arr=np.array([np.nan,23,4,345,546,56,67])

In [10]:
print(arr)

[ nan  23.   4. 345. 546.  56.  67.]


## copy array to another array

In [11]:
arr=np.array([1,2,3,4,5,6])

In [12]:
arr2=arr.copy()


In [13]:
arr2

array([1, 2, 3, 4, 5, 6])

## linespace in array

In [15]:
np.linspace(0,100) # arguments start and end

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [17]:
np.linspace(0,100,5) # args: start,end, how many points in between

array([  0.,  25.,  50.,  75., 100.])

In [30]:
arr=np.arange(8)

In [40]:
arr_reshape=np.reshape(arr,(2,4)) #np.reshape(array to be reshaped,(2 rows 4 columns))

In [41]:
np.reshape(arr,(-1,2,2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

##### We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.


### flattened the array

In [42]:
arr_reshape.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


In [45]:
## The matrix rows become columns after the transpose.

##### The function takes in a required first argument, which will be the array we want to transpose. It also has a single keyword argument called axes, which represents the new permutation of the dimensions.

##### The permutation is a tuple/list of integers, with the same length as the number of dimensions in the array. It tells us where to switch up the dimensions. For example, if the permutation had 3 at index 1, it means the old third dimension of the data becomes the new second dimension (since index 1 represents the second dimension).

##### The code below shows an example usage of the np.transpose function with the axes keyword argument. The shape property gives us the shape of an array

In [48]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes=(1, 2, 0))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format)

arr shape: (3, 4, 2)
<built-in method format of str object at 0x7f1cd0009e40>


In [49]:
np.zeros(4)

array([0., 0., 0., 0.])

In [50]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
np.ones((2,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

##### If we want to create an array of 0's or 1's with the same shape as another array, we can use np.zeros_like and np.ones_like.

In [54]:
arr = np.array([[1, 2], [3, 4]])
print("original array\n",arr)
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

original array
 [[1 2]
 [3 4]]
array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


#### Matrix multiplication


In [56]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))


27


In [57]:
np.sqrt(3-np.sqrt(2*np.sqrt(2)))

1.1481320348690611

### generating randeom numbers

In [67]:
np.random.randint(10) ## random number from 0 to 10

8

In [81]:
np.random.randint(5,high=10) #np.random.randint(low,high) will generate number between 5 to 10

9

In [91]:
np.random.randint(-3,high=14,size=(2,2)) #np.random.randint(low,high,size=(row,columns)) will generate number between 5 to 10

array([[ 0, 11],
       [12,  4]])

In [105]:
arr1=np.random.shuffle(np.array([2,3,4,5]))

In [106]:
print(arr1)

None


In [108]:
matrix=np.array([[1,2,3],[4,5,6],[6,7,8]])

In [109]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [111]:
print(np.random.shuffle(matrix))

None


In [115]:
np.random.uniform()

0.9928994892189393

In [125]:
np.random.uniform(10,20)

12.70443129616734

In [130]:

np.random.uniform(size=3)

array([0.25001696, 0.42689513, 0.64618524])

In [133]:
np.random.uniform(size=(2,2))

array([[0.5097316 , 0.83974852],
       [0.62596745, 0.1290568 ]])

In [134]:
random1=np.random.randint(5)

In [135]:
random1

2

In [144]:
np.random.randint((3,5))

array([1, 1])

In [147]:
colors=["red","blue","green"]


In [148]:
np.random.choice(colors)

'red'

In [149]:
np.random.choice(colors,size=2)

array(['blue', 'red'], dtype='<U5')

In [150]:
np.random.choice(colors,size=(2,3))

array([['red', 'green', 'green'],
       ['blue', 'red', 'blue']], dtype='<U5')

## indexing

In [151]:

arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [152]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [153]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


## Filtering

In [154]:
arr=np.array([[1,2,3],[4,5,6],[4,5,6]])

In [155]:
arr==3

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [158]:
arr[arr==3]

array([3])

In [159]:
arr>0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [160]:
arr[arr>0]

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [163]:
arr=np.array([[0,2,np.nan],[1,np.nan,-6],[np.nan,-2,1]])

In [164]:
arr

array([[ 0.,  2., nan],
       [ 1., nan, -6.],
       [nan, -2.,  1.]])

In [165]:
np.isnan(arr)


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [166]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


In [3]:
arr=np.array([[1,2,3],[1,3,-4],[-3,-2,1]])

#### Filtering in numpy

In [8]:
arr=np.array([0,3,5,3,1])

In [9]:
np.where(arr==3)

(array([1, 3]),)

In [10]:
arr=np.array([[0,2,3],[1,0,0],[-3,0,0]])

In [11]:
arr[np.where(arr!=0)]

array([ 2,  3,  1, -3])

In [12]:
arr=np.array([0,2,5,6,1])

In [13]:
arr[np.where(arr==3)]

array([], dtype=int64)

In [16]:
arr=np.array([[0,2,3],[1,0,0],[-3,0,0]])

In [17]:
x_ind,y_ind=np.where(arr!=0)

In [18]:
x_ind

array([0, 0, 1, 2])

In [19]:
y_ind

array([1, 2, 0, 0])

In [20]:
arr[x_ind,y_ind]

array([ 2,  3,  1, -3])

In [21]:
positive=np.array([[1,2],[3,4]])

In [22]:
negitive=np.array([[-2,5],[-1,-8]])

In [23]:
arr=np.array([[0,23,34],[1,3,5],[34,54,23]])

In [24]:
arr.min()

0

In [25]:
arr.max()

54

In [26]:
arr.min(axis=0)

array([0, 3, 5])

In [27]:
arr.max(axis=0)

array([34, 54, 34])

In [28]:
arr.min(axis=1)

array([ 0,  1, 23])

In [29]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

In [31]:
np.mean(arr)

2.0

In [32]:
np.var(arr)

977.3333333333334

In [33]:
np.median(arr)

1.0

In [34]:
np.median(arr,axis=1)

array([ 3.,  1., -2.])